config_path: /hdd/micro/SAHMI/scrna/sahmi_config_PRJ.yaml
Output_dir: /hdd/micro/SAHMI/scrna/PRJ
fq_path: /hdd/micro/dataset/PRJ
ncbi_blast: /hdd/envs/Scasa/bin
Kraken2Uniq_path: /hdd/micro/software/kraken2/kraken2
kraken_database_path: /hdd/micro/reference/DATABASE
umi: 10  #v2 10 v3 12
cb: 16  #v2 16 v3 16
R1: 1
R2: 2
sample: SRR14629324,SRR14629325
